version: '3'
services:
  app:
    build: .
    command: bin/dev
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle_app:/usr/local/bundle:cached
      - node_modules:/app/node_modules:cached

  node:
    image: node:latest
    working_dir: /app
    volumes:
      - .:/app
    volumes:
      - .:/app
      - node_modules:/app/node_modules:cached


volumes:
  bundle_app:
    driver: local
  node_modules:
    driver: local
